version: '3'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "/bin/sh"
    stdin_open: true
    tty: true
    volumes:
        - .:/app
    environment:
        ENV: "development"

networks:
  default:
    name: localdev
